name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install and Build
        run: |
          npm ci
          npm run build
          # Verify out/ exists (critical for Next.js export)
          ls -la out/

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2  # ← Key change: Use v2 instead of v3
        with:
          path: 'out'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2  # ← Key change: Use v2 instead of v3
